spring.application.name=med-center-api-v1
spring.datasource.url=jdbc:postgresql://localhost:5432/med-center
spring.datasource.username=root
spring.datasource.password=1033
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
